### ISSUE TITLE
How to use with a transitive grammar dependency?

### ISSUE THREAD

**Issue by trevor-e** [stackmystack/tsdl#13]
Hey,

Thanks for the project, been working great so far. I'm trying to use it with this grammar:
```
[parsers]
objc = { ref = "62e61b6f5c0289c376d61a8c91faf6435cde9012", from = "https://github.com/tree-sitter-grammars/tree-sitter-objc" }
```
But am getting a failure:
```
 × objc: Could not generate in tmp/objc
  ╰─▶   × [tmp/objc] tmp/tree-sitter-macos-arm64 generate failed with exit status 1.
        │ StdOut:
        │
        │ StdErr:
        │ node:internal/modules/cjs/loader:1143
        │   const err = new Error(message);
        │               ^
        │
        │ Error: Cannot find module 'tree-sitter-c/grammar'
        │ Require stack:
        │ - tmp/objc/grammar.js
        │     at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
        │     at Module._load (node:internal/modules/cjs/loader:984:27)
        │     at Module.require (node:internal/modules/cjs/loader:1231:19)
        │     at require (node:internal/modules/helpers:179:18)
        │     at Object.<anonymous> (/Users/telkins/dev/emerge/emerge-cli/tmp/objc/grammar.js:13:11)
        │     at Module._compile (node:internal/modules/cjs/loader:1369:14)
        │     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
        │     at Module.load (node:internal/modules/cjs/loader:1206:32)
        │     at Module._load (node:internal/modules/cjs/loader:1022:12)
        │     at cjsLoader (node:internal/modules/esm/translators:366:17) {
        │   code: 'MODULE_NOT_FOUND',
        │   requireStack: [ '/Users/telkins/dev/emerge/emerge-cli/tmp/objc/grammar.js' ]
        │ }
```
And looking at the Obj-C grammar I'm trying to use, it does have a Node dependency on the tree-sitter-c grammar. I tried including that in my `parsers.toml` as well but it didn't help resolve the dependency. Am I doing this wrong or is this not supported?

**Comment by stackmystack** [comment]
Hi,

I can't test locally, this will have to wait for tomorrow or the day after, but in your case, there is indeed dependency on `tree-sitter-c`; it's in the `package.json` of `tree-sitter-objc`.

In `tsdl`'s README, you can find an example for `typescript` that uses `cmd`. This will call your local shell and send it the text you provide. So maybe you can try:

```toml
objc = { ref = "62e61b6f5c0289c376d61a8c91faf6435cde9012", from = "https://github.com/tree-sitter-grammars/tree-sitter-objc", cmd = "node install && node build"}
```

???

**Comment by trevor-e** [comment]
Thank, I tried a few things with `cmd` and looks like it might be an underlying issue with this particular grammar, not `tsdl`. I see it has some grammar conflicts and fails to build:
```
        │ Unresolved conflict for symbol sequence:
        │
        │   '^'  identifier  •  'signed'  …
        │
        │ Possible interpretations:
        │
        │   1:  '^'  (_declarator  identifier)  •  'signed'  …                            (precedence: 0, associativity: Right)
        │   2:  '^'  (_type_specifier  identifier)  •  'signed'  …
        │   3:  '^'  (sized_type_specifier  identifier  •  sized_type_specifier_repeat1)
        │
        │ Possible resolutions:
        │
        │   1:  Specify a higher precedence in `sized_type_specifier` than in the other rules.
        │   2:  Specify a higher precedence in `_declarator` than in the other rules.
        │   3:  Specify a higher precedence in `_type_specifier` than in the other rules.
        │   4:  Specify a left or right associativity in `_declarator` and `_type_specifier`
        │   5:  Add a conflict for these rules: `_declarator`, `_type_specifier`, `sized_type_specifier`
```

**Comment by trevor-e** [comment]
Some upstream errors on the Obj-C grammar were fixed so tried again with `cmd = "npm install"`. This seems to fix the transitive dependency and conflicting grammar errors, but now I'm running into this:
```
Error: 
  × objc: Could not copy my-repo/parsers to my-repo/parsers/libtree-sitter-objc.dylib
  ╰─▶   × Couldn't find any dylib file
```

I see a `my-repo/tmp/objc/build` folder with stuff inside it, including a `tmp/objc/build/Release/tree_sitter_objc_binding.node` file, so looks like `tree-sitter generate` was doing some work in here but still won't convert to the final dylib.

**Comment by trevor-e** [comment]
OK I figured it out, I had some confusion on what `tsdl` was actually doing under the hood. I didn't realize that `tree-sitter build` is handling the dylib/so library creation. To fix all I had to do was:
```
cmd = "npm install && npx tree-sitter build"
```
and now it seems to work fine.

**Comment by stackmystack** [comment]
Great news, sorry I couldn't check your issue sooner, but indeed, there are some rough edges when it comes to tree-sitter parser building.

Most of the officially maintained ones build nicely and similarly, that's why you don't have to pass `cmd` for them.
